[package]
name = "rustfun"
version = "0.1.0"
authors = ["Chao Sun <sunchao@apache.org>"]

[dependencies]
### For Protobuf
grpc            = "0.*"
protobuf        = "1.*"
futures         = "0.1"
futures-cpupool = "0.1"
